version: '3.9'

services:

  database:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: psw1234
      MYSQL_DATABASE: u65042380121
      MYSQL_USER: bee
      MYSQL_PASSWORD: psw1234
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
    ports:
      - 3307:3306
    volumes:
      - ./employee.sql:/docker-entrypoint-initdb.d/employee.sql
    # restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - mynetwork
  backend:
    build: ./backend/
    ports:
      - 6530:6530
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_USER: bee
      DB_PASSWORD: psw1234
      DB_DATABASE: u65042380121
    networks:
      - mynetwork
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    environment:
      - http://localhost:6530
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
